//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Account = new HashSet<Account>();
            this.Account1 = new HashSet<Account>();
            this.Contact = new HashSet<Contact>();
            this.Contact1 = new HashSet<Contact>();
            this.Inventory = new HashSet<Inventory>();
            this.Leads = new HashSet<Leads>();
        }
    
        public int AddressId { get; set; }
        public Nullable<int> SingleAddressId { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<Account> Account1 { get; set; }
        public virtual Address_Type Address_Type { get; set; }
        public virtual All_Address All_Address { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ICollection<Leads> Leads { get; set; }
    }
}
