//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Address
    {
        public All_Address()
        {
            this.Address = new HashSet<Address>();
        }
    
        public int SingleAddressId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<decimal> ZipCode { get; set; }
        public Nullable<int> StateId { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual State State { get; set; }
    }
}
