//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign_Customer
    {
        public int CampaignContactsId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> OpportunityId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
