//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Level_Languages
    {
        public Contact_Level_Languages()
        {
            this.Contact = new HashSet<Contact>();
        }
    
        public int ContactLevelLanguagesId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> LevelLanguageId { get; set; }
    
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual Language Language { get; set; }
        public virtual Level_Language Level_Language { get; set; }
    }
}
