//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.Cases = new HashSet<Case>();
            this.Contact1 = new HashSet<Contact>();
        }
    
        public int ContactId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SalutationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> ContactReportToId { get; set; }
        public Nullable<int> LeadSourceId { get; set; }
        public string PhoneNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string OtherPhoneMobile { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public string Assitant { get; set; }
        public string AssitantPhoneNumber { get; set; }
        public Nullable<int> ContactMailingAddressId { get; set; }
        public Nullable<int> ContactOtherAddressId { get; set; }
        public Nullable<int> ContactLevelLanguagesId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual Contact Contact2 { get; set; }
        public virtual Contact_Level_Languages Contact_Level_Languages { get; set; }
        public virtual Lead_Source Lead_Source { get; set; }
        public virtual Salutation Salutation { get; set; }
        public virtual User User { get; set; }
    }
}
