//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry
    {
        public Industry()
        {
            this.Account = new HashSet<Account>();
            this.Competidors = new HashSet<Competidors>();
            this.Competidors1 = new HashSet<Competidors>();
            this.Leads = new HashSet<Leads>();
            this.Competidors11 = new HashSet<Competidors>();
        }
    
        public int IndustryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<Competidors> Competidors { get; set; }
        public virtual ICollection<Competidors> Competidors1 { get; set; }
        public virtual ICollection<Leads> Leads { get; set; }
        public virtual ICollection<Competidors> Competidors11 { get; set; }
    }
}
