//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Products
    {
        public int InventoryProductId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> InventoryId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Products Products { get; set; }
    }
}
