//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead_Source
    {
        public Lead_Source()
        {
            this.Contacts = new HashSet<Contact>();
            this.Leads = new HashSet<Lead>();
        }
    
        public int LeadSourceId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
    }
}
