//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level_Language
    {
        public Level_Language()
        {
            this.Contact_Level_Languages = new HashSet<Contact_Level_Languages>();
        }
    
        public int LevelLanguageId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Contact_Level_Languages> Contact_Level_Languages { get; set; }
    }
}
