//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects_Views
    {
        public int ObjectsViewsId { get; set; }
        public string name { get; set; }
        public Nullable<int> objectid { get; set; }
    
        public virtual Objects Objects { get; set; }
    }
}
