//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objects
    {
        public Objects()
        {
            this.Object_Fields = new HashSet<Object_Fields>();
            this.Profile_Object = new HashSet<Profile_Object>();
        }
    
        public int ObjectId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Object_Fields> Object_Fields { get; set; }
        public virtual ICollection<Profile_Object> Profile_Object { get; set; }
    }
}
