//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunities
    {
        public Opportunities()
        {
            this.Opportunities_Products = new HashSet<Opportunities_Products>();
        }
    
        public int OpportunityId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> OpportunityTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string NextStep { get; set; }
        public Nullable<int> OpportunityStageId { get; set; }
        public Nullable<decimal> Probability { get; set; }
        public Nullable<int> CampaignPrimarySourceId { get; set; }
        public string OrderNumber { get; set; }
        public string CurrentGenerator { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> OpportunityStatusId { get; set; }
        public Nullable<int> CompetidorId { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Private { get; set; }
        public Nullable<System.DateTime> ViewDate { get; set; }
        public Nullable<bool> HiddenOpportunity { get; set; }
        public Nullable<int> LeadSourceId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual Competidors Competidors { get; set; }
        public virtual Opportunities_Stage Opportunities_Stage { get; set; }
        public virtual Opportunities_Status Opportunities_Status { get; set; }
        public virtual Opportunities_Type Opportunities_Type { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<Opportunities_Products> Opportunities_Products { get; set; }
        public virtual Lead_Source Lead_Source { get; set; }
    }
}
