//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunities_Products
    {
        public int OpportunityProductId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> OpportunityId { get; set; }
    
        public virtual Opportunity Opportunity { get; set; }
        public virtual Product Product { get; set; }
    }
}
