//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunities_Competidor
    {
        public Opportunities_Competidor()
        {
            this.Opportunities = new HashSet<Opportunity>();
        }
    
        public int OpportunityCompetidorId { get; set; }
        public string Name { get; set; }
        public string Strenghts { get; set; }
        public string Weakness { get; set; }
    
        public virtual ICollection<Opportunity> Opportunities { get; set; }
    }
}
