//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportunities_Status
    {
        public Opportunities_Status()
        {
            this.Opportunities = new HashSet<Opportunities>();
        }
    
        public int OpportunityStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Opportunities> Opportunities { get; set; }
    }
}
