//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Cases = new HashSet<Cases>();
            this.Inventory_Products = new HashSet<Inventory_Products>();
            this.Opportunities_Products = new HashSet<Opportunities_Products>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> HiddenProduct { get; set; }
    
        public virtual ICollection<Cases> Cases { get; set; }
        public virtual ICollection<Inventory_Products> Inventory_Products { get; set; }
        public virtual ICollection<Opportunities_Products> Opportunities_Products { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
