//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public Rating()
        {
            this.Accounts = new HashSet<Account>();
            this.Leads = new HashSet<Lead>();
        }
    
        public int RatingId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Value { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
    }
}
