//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int RecordId { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
