//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.Accounts1 = new HashSet<Account>();
            this.Accounts2 = new HashSet<Account>();
            this.Campaigns = new HashSet<Campaign>();
            this.Campaigns1 = new HashSet<Campaign>();
            this.Campaigns2 = new HashSet<Campaign>();
            this.Cases = new HashSet<Case>();
            this.Cases1 = new HashSet<Case>();
            this.Cases2 = new HashSet<Case>();
            this.Contacts = new HashSet<Contact>();
            this.Contacts1 = new HashSet<Contact>();
            this.Contacts2 = new HashSet<Contact>();
            this.Leads = new HashSet<Lead>();
            this.Leads1 = new HashSet<Lead>();
            this.Leads2 = new HashSet<Lead>();
            this.Opportunities = new HashSet<Opportunity>();
            this.Opportunities1 = new HashSet<Opportunity>();
            this.Opportunities2 = new HashSet<Opportunity>();
            this.Products = new HashSet<Product>();
            this.Products1 = new HashSet<Product>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string HashPassword { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Account> Accounts1 { get; set; }
        public virtual ICollection<Account> Accounts2 { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Campaign> Campaigns1 { get; set; }
        public virtual ICollection<Campaign> Campaigns2 { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Case> Cases1 { get; set; }
        public virtual ICollection<Case> Cases2 { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Contact> Contacts1 { get; set; }
        public virtual ICollection<Contact> Contacts2 { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Lead> Leads1 { get; set; }
        public virtual ICollection<Lead> Leads2 { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Opportunity> Opportunities1 { get; set; }
        public virtual ICollection<Opportunity> Opportunities2 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
