//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Account = new HashSet<Account>();
            this.Account1 = new HashSet<Account>();
            this.Account2 = new HashSet<Account>();
            this.Campaign = new HashSet<Campaign>();
            this.Campaign1 = new HashSet<Campaign>();
            this.Campaign2 = new HashSet<Campaign>();
            this.Cases = new HashSet<Cases>();
            this.Cases1 = new HashSet<Cases>();
            this.Cases2 = new HashSet<Cases>();
            this.Contact = new HashSet<Contact>();
            this.Contact1 = new HashSet<Contact>();
            this.Contact2 = new HashSet<Contact>();
            this.Leads = new HashSet<Leads>();
            this.Leads1 = new HashSet<Leads>();
            this.Leads2 = new HashSet<Leads>();
            this.Opportunities = new HashSet<Opportunities>();
            this.Opportunities1 = new HashSet<Opportunities>();
            this.Opportunities2 = new HashSet<Opportunities>();
            this.Products = new HashSet<Products>();
            this.Products1 = new HashSet<Products>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string HashPassword { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<Account> Account1 { get; set; }
        public virtual ICollection<Account> Account2 { get; set; }
        public virtual ICollection<Campaign> Campaign { get; set; }
        public virtual ICollection<Campaign> Campaign1 { get; set; }
        public virtual ICollection<Campaign> Campaign2 { get; set; }
        public virtual ICollection<Cases> Cases { get; set; }
        public virtual ICollection<Cases> Cases1 { get; set; }
        public virtual ICollection<Cases> Cases2 { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Contact> Contact1 { get; set; }
        public virtual ICollection<Contact> Contact2 { get; set; }
        public virtual ICollection<Leads> Leads { get; set; }
        public virtual ICollection<Leads> Leads1 { get; set; }
        public virtual ICollection<Leads> Leads2 { get; set; }
        public virtual ICollection<Opportunities> Opportunities { get; set; }
        public virtual ICollection<Opportunities> Opportunities1 { get; set; }
        public virtual ICollection<Opportunities> Opportunities2 { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Products> Products1 { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
