//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.Campaigns = new HashSet<Campaign>();
            this.Cases = new HashSet<Case>();
            this.Contacts = new HashSet<Contact>();
            this.Leads = new HashSet<Lead>();
            this.Opportunities = new HashSet<Opportunity>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string HashPassword { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
