//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCRM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Account = new HashSet<Account>();
            this.Campaign = new HashSet<Campaign>();
            this.Cases = new HashSet<Cases>();
            this.Contact = new HashSet<Contact>();
            this.Leads = new HashSet<Leads>();
            this.Opportunities = new HashSet<Opportunities>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string HashPassword { get; set; }
        public Nullable<int> ProfileId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual ICollection<Campaign> Campaign { get; set; }
        public virtual ICollection<Cases> Cases { get; set; }
        public virtual ICollection<Contact> Contact { get; set; }
        public virtual ICollection<Leads> Leads { get; set; }
        public virtual ICollection<Opportunities> Opportunities { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
